Feature/con 2212/log modal refactor
ConductionNL/commonground-gateway-frontend pull request #54
Opened 2022-01-21 09:54 UTC by bbrands02

2022-01-21 11:06 UTC, lencodes requested changes
Ziet er goed uit, zie nog wel wat verbeterpunten.

2022-01-21 11:06 UTC, lencodes commented on pwa/src/components/logs/logTable.tsx
> +                    <h5 className="utrecht-heading-5 utrecht-heading-5--distanced mt-1">Status: {log.requestStatus && log.requestStatus} <b style={{ color: log.responseStatusCode > 199 && log.respons
Ik denk dat dit een tabel moet worden i.p.v. dat het een aantal `<h5>` elementen zijn.

Ik zie een hoop `log.routeName && log.routeName`, wat is de reden voor deze syntax? Volgens mij zou enkel `log.routeName` hetzelfde doel bereiken.

2022-01-21 11:06 UTC, lencodes commented on pwa/src/components/logs/logTable.tsx
> +                    <h5 className="utrecht-heading-5 utrecht-heading-5--distanced mt-1">Path info: {log.requestPathInfo && log.requestPathInfo}</h5>
Haakt in op bovenstaande comment:

Ik denk dat je hier een check doet of `log.requestMethod` bestaat en wanneer die bestaat je hem wilt tonen. Een makkelijkere manier hiervoor zou zijn `log?.requestMethod`.

2022-01-21 11:06 UTC, lencodes commented on pwa/src/components/logs/logTable.tsx
> +                                  <code id="requestContent" style={{ color: 'orange' }} className="language-json">
Ook deze styling wordt nu dubbel geschreven.

2022-01-21 11:06 UTC, lencodes commented on pwa/src/components/logs/logTable.tsx
> +                                  <code id="requestContent" style={{ color: 'orange' }} className="language-json">
Heel het content onderdeel wordt eigenlijk dubbel geschreven, misschien dat het een idee is om (in hetzelfde bestand) een extra component aan te maken e.g.:

```
const CodeContent: React.FC<..> = () => {
  // logica van dit component
}
```

En deze kan je dan tweemaal includen i.p.v. dat je de code tweemaal schrijft.

2022-01-26 13:28 UTC, smisidjan approved these changes

2022-01-26 13:49 UTC, merged